(function(){
    angular
        .module("mealBuilderPlusApp",[
            "ngRoute",
            "ui.bootstrap",
            "ngAnimate",
            "angularUtils.directives.dirPagination"
        ]);
}());
